version: '3'
services:
  bar-service:
    build:
      context: ../bar-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_USR: ${CONFIG_SERVER_USR}
      CONFIG_SERVER_PWD: ${CONFIG_SERVER_PWD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://bar-db:5432/bar
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - bar-network
      - backend-network

  happy-hour-service:
    build:
      context: ../happy-hour-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_USR: ${CONFIG_SERVER_USR}
      CONFIG_SERVER_PWD: ${CONFIG_SERVER_PWD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://happy-hour-db:5432/happy-hour
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - happy-hour-network
      - backend-network

  bar-composite:
    build:
      context: ../bar-composite
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_USR: ${CONFIG_SERVER_USR}
      CONFIG_SERVER_PWD: ${CONFIG_SERVER_PWD}
    networks:
      - backend-network

  trip-service:
    build:
      context: ../trip-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_USR: ${CONFIG_SERVER_USR}
      CONFIG_SERVER_PWD: ${CONFIG_SERVER_PWD}
    networks:
      - backend-network

  gateway:
    restart: always
    build:
      context: ../api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_USR: ${CONFIG_SERVER_USR}
      CONFIG_SERVER_PWD: ${CONFIG_SERVER_PWD}
    networks:
      - backend-network
    ports:
     - "9090:9090"

networks:
  backend-network:
    driver: bridge
  bar-network:
    driver: bridge
  happy-hour-network:
    driver: bridge
